"""移除API_KEY和API_USAGE_LOG,添加COLLECTION_SHARE表

Revision ID: e841d98e7989
Revises: b4c10b64cf8e
Create Date: 2025-10-30 10:59:26.710113

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e841d98e7989"
down_revision: str | Sequence[str] | None = "b4c10b64cf8e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection_shares",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("share_token", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("search_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["collection_id"], ["collections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_share_active", "collection_shares", ["is_active"], unique=False)
    op.create_index("idx_share_creator", "collection_shares", ["created_by"], unique=False)
    op.create_index("idx_share_kb", "collection_shares", ["collection_id"], unique=False)
    op.create_index("idx_share_token", "collection_shares", ["share_token"], unique=False)
    op.create_index(op.f("ix_collection_shares_share_token"), "collection_shares", ["share_token"], unique=True)
    op.drop_index(op.f("idx_aul_api_key"), table_name="api_usage_logs")
    op.drop_index(op.f("idx_aul_created_at"), table_name="api_usage_logs")
    op.drop_index(op.f("idx_aul_endpoint"), table_name="api_usage_logs")
    op.drop_index(op.f("idx_aul_status"), table_name="api_usage_logs")
    op.drop_index(op.f("idx_aul_user"), table_name="api_usage_logs")
    op.drop_table("api_usage_logs")
    op.drop_index(op.f("idx_ak_active"), table_name="api_keys")
    op.drop_index(op.f("idx_ak_hash"), table_name="api_keys")
    op.drop_index(op.f("idx_ak_kb"), table_name="api_keys")
    op.drop_index(op.f("idx_ak_user"), table_name="api_keys")
    op.drop_table("api_keys")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_keys",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("collection_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("key_hash", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("key_prefix", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
        sa.Column("key_suffix", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
        sa.Column("scopes", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("rate_limit", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("daily_quota", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("monthly_quota", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("usage_count_today", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("usage_count_month", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("last_used_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("last_used_ip", sa.VARCHAR(length=45), autoincrement=False, nullable=True),
        sa.Column("security", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["collection_id"], ["collections.id"], name="api_keys_collection_id_fkey"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="api_keys_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="api_keys_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(op.f("idx_ak_user"), "api_keys", ["user_id"], unique=False)
    op.create_index(op.f("idx_ak_kb"), "api_keys", ["collection_id"], unique=False)
    op.create_index(op.f("idx_ak_hash"), "api_keys", ["key_hash"], unique=False)
    op.create_index(op.f("idx_ak_active"), "api_keys", ["is_active"], unique=False)
    op.create_table(
        "api_usage_logs",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("api_key_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("endpoint", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column("method", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
        sa.Column("status_code", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("response_time_ms", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("request_body", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("ip_address", sa.VARCHAR(length=45), autoincrement=False, nullable=False),
        sa.Column("user_agent", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["api_key_id"], ["api_keys.id"], name=op.f("api_usage_logs_api_key_id_fkey")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("api_usage_logs_user_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("api_usage_logs_pkey")),
    )
    op.create_index(op.f("idx_aul_user"), "api_usage_logs", ["user_id"], unique=False)
    op.create_index(op.f("idx_aul_status"), "api_usage_logs", ["status_code"], unique=False)
    op.create_index(op.f("idx_aul_endpoint"), "api_usage_logs", ["endpoint"], unique=False)
    op.create_index(op.f("idx_aul_created_at"), "api_usage_logs", ["created_at"], unique=False)
    op.create_index(op.f("idx_aul_api_key"), "api_usage_logs", ["api_key_id"], unique=False)
    op.drop_index(op.f("ix_collection_shares_share_token"), table_name="collection_shares")
    op.drop_index("idx_share_token", table_name="collection_shares")
    op.drop_index("idx_share_kb", table_name="collection_shares")
    op.drop_index("idx_share_creator", table_name="collection_shares")
    op.drop_index("idx_share_active", table_name="collection_shares")
    op.drop_table("collection_shares")
    # ### end Alembic commands ###
